CREATE database farmermarcket;
use farmermarcket;

-- drop database Onlinemarketplace;

-- ======= TABLE ========

CREATE TABLE USERS (
USER_ID INT NOT NULL AUTO_INCREMENT,
PAYMENT_ID INT NOT NULL,
USER_NAME VARCHAR (50) NOT NULL,
USER_PASSWORD VARCHAR (50) NOT NULL,
USER_AGE INT NOT NULL,
DATE_OF_BIRTH DATE NULL NULL,
EMAIL VARCHAR(50) NOT NULL,
STATE VARCHAR (50) NOT NULL,
STREET VARCHAR (50) NOT NULL,
CITY VARCHAR (50) NOT NULL,
ZIP_CODE INT NOT NULL,
CONSTRAINT pk_users primary key(USER_ID),
CONSTRAINT unique_username unique (USER_NAME),
CONSTRAINT unique_email unique(EMAIL)

);
